/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}',
    '../../packages/ui/src/**/*.{ts,tsx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        ae: {
          bg: 'var(--ae-bg)',
          fg: 'var(--ae-fg)',
          surface: 'var(--ae-surface)',
          'surface-secondary': 'var(--ae-surface-secondary)',
          border: 'var(--ae-border)',
          'border-light': 'var(--ae-border-light)',
          'border-strong': 'var(--ae-border-strong)',
          'text-primary': 'var(--ae-text-primary)',
          'text-secondary': 'var(--ae-text-secondary)',
          'text-muted': 'var(--ae-text-muted)',
          'text-disabled': 'var(--ae-text-disabled)',
          hover: 'var(--ae-hover)',
          active: 'var(--ae-active)',
          'focus-ring': 'var(--ae-focus-ring)',
          overlay: 'var(--ae-overlay)',
          backdrop: 'var(--ae-backdrop)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'Geist', 'SF Pro Display', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'SF Mono', 'Cascadia Code', 'Consolas', 'monospace'],
      },
      fontSize: {
        'ae-xs': ['0.75rem', { lineHeight: '1.5', letterSpacing: '0.01em' }],
        'ae-sm': ['0.8125rem', { lineHeight: '1.5' }],
        'ae-base': ['0.875rem', { lineHeight: '1.5' }],
        'ae-md': ['0.9375rem', { lineHeight: '1.5' }],
        'ae-lg': ['1.0625rem', { lineHeight: '1.5' }],
        'ae-xl': ['1.25rem', { lineHeight: '1.15' }],
        'ae-2xl': ['1.5rem', { lineHeight: '1.15' }],
        'ae-3xl': ['1.875rem', { lineHeight: '1.15' }],
        'ae-4xl': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.015em' }],
      },
      spacing: {
        'ae-1': '0.25rem',
        'ae-2': '0.5rem',
        'ae-3': '0.75rem',
        'ae-4': '1rem',
        'ae-5': '1.25rem',
        'ae-6': '1.5rem',
        'ae-8': '2rem',
        'ae-12': '3rem',
        'ae-16': '4rem',
        'ae-24': '6rem',
      },
      borderRadius: {
        'ae-sm': '4px',
        'ae-md': '6px',
        'ae-lg': '8px',
        'ae-xl': '12px',
      },
      boxShadow: {
        'ae-none': 'var(--ae-shadow-none)',
        'ae-xs': 'var(--ae-shadow-xs)',
        'ae-sm': 'var(--ae-shadow-sm)',
        'ae-md': 'var(--ae-shadow-md)',
        'ae-lg': 'var(--ae-shadow-lg)',
        'ae-overlay': 'var(--ae-shadow-overlay)',
      },
      transitionDuration: {
        'ae-fast': '100ms',
        'ae-normal': '150ms',
        'ae-slow': '200ms',
      },
    },
  },
  plugins: [],
}
